### ISSUE TITLE
Getting build errors compiling musicstore

### ISSUE THREAD

**Issue by suthrams** [aspnet/MusicStore#374]
Folks

I am getting started with aspnet vnext and would like to build and run music store on my box. I installed vs 2015, set up kre etc

I opened the solution and tried to build and got a ton of errors (29371) of them. I need help to see the work you guys are doing to port this over to vnext.

Any pointers appreciated. 
Thanks

**Comment by Praburaj** [comment]
@suthrams are you on master branch or dev branch?

**Comment by suthrams** [comment]
I forked off the master branch

**Comment by Praburaj** [comment]
Do you see the packages are restored successfully in VS references node?

**Comment by suthrams** [comment]
I see the packages restored successfully with no exclamations. But even very basic system.void is not being recognized.. I can paste some build output if it helps

**Comment by suthrams** [comment]
Here is some more info 
1) Forked music store
2) Checked to make sure the latest kre ws installed for my user profile for core clr and clr 
3) Opened the solution VS 2015 CTP 5 and did a build.  All the packages were restored.

**Comment by Praburaj** [comment]
What's the version of KRE you are using. You can go to project's properties and see that in the drop down. 

And all the restored packages are `beta2`

**Comment by WillBaldwin** [comment]
I have an issue has seems similar..  (see screenshot)

Note that not even "use System" resolves, intellisence is completely nonfunctional; the document outline is empty.  "KPM restore" grabs all the packages without errors.  Is this what you are experiencing?

![screenshot_musicstore](https://cloud.githubusercontent.com/assets/5522137/5966012/52a773f2-a7c6-11e4-9c6c-c89e80ee6432.png)

**Comment by suthrams** [comment]
Yes. I am seeing the same behavior

**Comment by heathyates** [comment]
I am also observing this behavior.

**Comment by victorhurdugaci** [comment]
From what branch is the Music Store code?

**Comment by WillBaldwin** [comment]
I just cloned https://github.com/aspnet/MusicStore.git

**Comment by Praburaj** [comment]
Could you try running from command line to see if it works successfully? Instructions for running on weblistener or kestrel are in the repo readme.

**Comment by WillBaldwin** [comment]
It builds, I assume it runs command line but will check and report.  The issue seems to be the VS editor and intellisense.

**Comment by heathyates** [comment]
@Praburaj I also cloned from the master branch like @WillBaldwin and @suthrams. As the first screenshot shows above, it is like VS15 cannot find the dependencies that the project is bringing it. We can "build" it just fine, but it won't compile and/or run.

**Comment by WillBaldwin** [comment]
This issue seems to be easily reproducible and following the steps a normal reasonable developer would try:

(1) Build Windows 8.1 VM
(2) Install VS2015 CTP5
(3) Clone Music Store
(4) Open the solution
(5) Open startup.cs
(6) Observe strange IDE Editor/Intellisense behavior (see above screen shots)


Attempt to troubleshoot
(1) restart Visual Studio 2015 CTP 5
(2) reboot computer
(3) kvm upgrade
(4) kpm restore
(5) double-check target kre in the project settings
(6) double-check target kre in navigation bar
(7) find wall to bang head against
(8) bang head

It seems incredible that the Music Store development team has not experienced this issue.  Would it not be more likely that they found a fix and we just don't know it yet?   Help!  My head hurts (see troubleshooting step 8).

**Comment by Praburaj** [comment]
@WillBaldwin @suthrams I'll give it a try today and update the bug with information.

**Comment by heathyates** [comment]
@Praburaj, have you found anything since Friday? I am still experiencing the issue, but felt the following information could be valuable to your efforts. These are the steps I take to duplicate this issue. 

Step 0: This occurs as soon as I clone the repo: 
![error0](https://cloud.githubusercontent.com/assets/1896424/6007891/3590a818-aae3-11e4-9a0c-7acb3a9b78e3.PNG)

Step 1: I update the packages (from both nugget and nightly build) 
![step1](https://cloud.githubusercontent.com/assets/1896424/6007923/56d100ae-aae3-11e4-8a04-39cef11cb896.PNG)

Step 2: I try to launch the application, but receive building errors
![step2](https://cloud.githubusercontent.com/assets/1896424/6007927/5c9a7182-aae3-11e4-9eaa-8d6c66a236e8.PNG)

Step 3: These are some of the errors observed
![step3](https://cloud.githubusercontent.com/assets/1896424/6007939/7c32d6ec-aae3-11e4-94f4-c4a668b74f67.PNG)

Step 4: Observing even more errors by looking at other files (dependencies are not being found) 
![step4](https://cloud.githubusercontent.com/assets/1896424/6007969/a5f9538e-aae3-11e4-9eef-b730e6462f15.PNG)

Step 5: Checking another startup.cs, more the same 
![step5](https://cloud.githubusercontent.com/assets/1896424/6007983/b9073e3c-aae3-11e4-8b63-b7b49734b444.PNG)

Step 6: Making sure I have the dependencies in the project, yes. 
![step6](https://cloud.githubusercontent.com/assets/1896424/6007987/c1668678-aae3-11e4-81da-0f24ea6c296f.PNG)

Step 7: Probably should let you know what version of VS15 I'm using 
![step7](https://cloud.githubusercontent.com/assets/1896424/6007999/d6954a20-aae3-11e4-96f5-d25e52a4d10a.PNG)

Step 8: Sanity check, making sure I got the newest version of kvm that I can 
![step8](https://cloud.githubusercontent.com/assets/1896424/6008005/e303ec12-aae3-11e4-9ff8-969d80b420a9.PNG)

@Praburaj, I experience this issue both on my surface (which isn't a VM) and my VM. My gut tells me that this could be a wider issue than just mvcmusic store.

**Comment by WillBaldwin** [comment]
I have discovered that if I gut the code... delete all the files...  delete even startup.cs  and delete project.json then create a new class file I can get intellisense to resolve System...   I can recreate an empty startup.cs then recreate an empty project.json and it will still behave.   

So now I have a gutted project that seems ok for now... and a MusicStore project that still will not resolve references to System within the IDE. So now I have it in a project specific state...

Tomorrow I will start adding code back into the gutted project to see what in project.json it causing the problem.

**Comment by heathyates** [comment]
@Praburaj @suthrams I am using the master branch. The issue for me was the version of KRE and the packages in package.json did not match. So I explicitly told it to use ONLY NuGet.org and beta2. 

@WillBaldwin Reported to me that he discovered independently that you can only point the application at one nuget source at a time or you will get aberrant behavior. Also, to choose the NuGet source appropriate to what your doing.  

This solved the problem for me. Second, I believe that if you use the nightly build or dev branch, you also need to have the most up to date KRE to be compatible. See: https://github.com/aspnet/Home

**Comment by suthrams** [comment]
Folks

I am back to looking into this. Can somebody post the instructions as to what needs to be done after clone to get this to build.  

How do we tell explicitly to use nugget.org and beta 2? What changes needs to be done in package.json. 

Thanks

**Comment by heathyates** [comment]
@suthrams Eilion answered this on stackoverflow for me. See: http://stackoverflow.com/questions/28335972/cannot-get-dependencies-packages-to-be-recognized-in-source-files-of-asp-net-mvc

I think this issue should be closed.

**Comment by Praburaj** [comment]
Sorry everyone for the late reply. We found a few more issues while investigating this: 
1.       Tooling disables the nuget.org feed while loading the solution resulting in package restore failures. Work around is to go and manually enable the feed after launching the solution. To restore the packages go ahead and hit save on the project.json files. Note: See (3) below before hitting save. 
2.       There are a few build errors in the .net 4.5 version of both MusicStore projects due to this checkin - https://github.com/aspnet/MusicStore/commit/715b744146ccd521b2c8a5d1d6d25757489d0dd3. I will be pushing a fix shortly to fix this. 
3.       All project.json’s contain ‘*’ in their version numbers. So while restoring packages it pulls the absolute latest rather than beta2. We are going to lock build numbers in project.json to avoid these kinds of issues in future. Until this is fixed please change all `*` in project.json files to `beta2`. 
4.       Xunit.KRunner package seems to be missing in nuget.org. This results in many build errors in the test project. With the upcoming release we are changing to an official xunit runner. So we will not be pushing this package to nuget.org. Work around is to unload the E2ETests project from the solution. 

Let us know if

**Comment by heathyates** [comment]
@Praburaj Thank you for your reply. This is really useful information and I know your team is rapidly developing, so it can be hard to keep up with everything. 

That being said, may I have your ear for a moment please @Praburaj? I have two things I would like to ask below: 

1. You mentioned that Xunit.KRunner package seems to be missing in nugget.org, and I have noticed that I can never get it to work. So your fix is super useful for not only the store, but my other applications. Additionally, are there any new Xunit tests coming as well? I looked at the source code and as far as I can tell, there are no examples on how to test the CRUD operations in the MVC framework. Can all the above be a priority? It feels really gross developing or working on an application without testing. 

2. It seems all master builds everywhere are beta2. Do you have an idea when beta3 will be coming out? I am sure you probably can't answer this specifically and I won't hold you to a guestimate. So something like a month? Two months? 

Thanks to you and your team.

**Comment by suthrams** [comment]
@Praburaj Thank you for your reply. I was able to build today following the instructions to re-save project json and changing to beta2 which seems to have been already there. I unloaded the xunit.krunner.  Thanks to all who helped.  I will close this issue

**Comment by Praburaj** [comment]
@suthrams @heathyates Thanks for your patience. I pushed a change to the master branch to fix (2) and (3) above. So you should be good on those fronts. 

(1) is a known issue http://nuget.codeplex.com/workitem/4397. A good work around will be to create a Nuget package source named `NugetTotal` with the same feed url as `Nuget.org` in the nuget package sources dialog. This will make sure that the feed is not automatically disabled. 

@heathyates - regarding your question on testing MVC CRUD operations. MusicStore tests are meant to do only end to end testing simulating how the application works on the browser. However I know there is a unit test framework in progress for testing MVC. @yishaigalatzer @ianhong can provide details on that for you on that. 

And regarding beta3 release dates - @danroth27 can you answer this?

**Comment by ianhong** [comment]
@suthrams 
Actually we modified the MVC framwork to make controllers more unit-testable. And, we already updated the MusicStore sample for that matter. I'm about to add sample unit tests for those MusicStore controllers, and I think you will see them in a week or so..

**Comment by suthrams** [comment]
One more minor addition. Instead of unloading the test project. I commented the xunit.krunner and replaced it with this entry in project.json for the test project. After that I was able to compile the entire solution and also get back my intellisense that was missing badly.

        "xunit.runner.kre":  "1.0.0-beta4-1053", 
        //   "Xunit.KRunner": "1.0.0-*",

**Comment by suthrams** [comment]
And I got this feed added temporarily in VS 2015 http://www.myget.org/F/xunit

**Comment by Praburaj** [comment]
@suthrams - we have seen at many times `beta4` bits does not work very well with `beta2` KREs or similar. But :+1: if that works for you :smile:

**Comment by heathyates** [comment]
@ianhong Thanks for your reply. I am looking forward to your xunit contributions. Can you please tell me where I can find other sample code for beta2 xunit MVC Crud examples?

**Comment by heathyates** [comment]
@ianhong Any update regarding sample unit tests for MusicStore controllers? Any good references to point me to for studying code implementation of xunit tests for beta3?

**Comment by Praburaj** [comment]
@heathyates - there are already a few PRs open on this repo to add unit tests. Have a look at them.
