### ISSUE TITLE
what is the test folder? And I how to use it?

### ISSUE THREAD

**Issue by i542873057** [aspnet/MusicStore#750]
i am a Novice.   i see a test folder in the root directory.  what is it use to ?

**Comment by pranavkm** [comment]
@i542873057 the test folder has some of the tests we use to verify AspNetCore's end-to-end scenarios using the MusicStore sample. I wouldn't recommend not using this repository for learning Asp.Net since it has some atypical code designed around how we build and test our repositories. https://docs.microsoft.com/en-us/aspnet/core/ has great getting started guides.
