### ISSUE TITLE
Re-enable tests disabled by cookie path changes

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#804]
External issue: https://github.com/dotnet/corefx/issues/18013 & https://github.com/dotnet/corefx/issues/21250

**Comment by pranavkm** [comment]
Changes to revert https://github.com/aspnet/MusicStore/pull/803/commits/06673e081add22d7bb2dcc2349334cf297c28da1

**Comment by Eilon** [comment]
@javiercn - is this something we can do a workaround for in 2.0.0?

**Comment by javiercn** [comment]
@Eilon I'm looking into it. I discussed with @Tratcher and we are trying to workaround HttpClient limitations on the test itself. If i'm not able to do so, I will workaround it by configuring the path on the cookie dynamically based on the presence of a header and I will make HttpClient in that test send that header.

Essentially so that F5 works like in a real world scenario, and the tests work almost like a real world scenario except for the cookie path.
